# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b61cfd667123c987d236fe5ed0dafa7f537b3507af44425f8112f32737c21c1f2d0492138e151aada70a95dc71bf49d9050ab2365b757bebe5aedd5602bf423a

test:
  secret_key_base: f7c2260fb9924d084753eb29ce664480653c8efd81dcb1660d16fdf106ba999fac6dbcce53e7c724ada59ce3de03dbeba2ef398c58937bbfaeee0c80165afca8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
